projects:
  amplifynotetaker:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: hfysqf6oavdmjkj5fyrk46ncfm
      endpoints:
        prod: >-
          https://dvjdmdbfvjgcdnkvsg6tted2yq.appsync-api.us-west-2.amazonaws.com/graphql
