// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:111619e1-4563--bfed-57bacfe31d18",
    "aws_cognito_region": "us--2",
    "aws_user_pools_id": "us-west-",
    "aws_user_pools_web_client_id": "",
    "aws_appsync_graphqlEndpoint": "https://l",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
