// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:111619e1-4563-44b8-bfed-57bacfe31d18",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Y9FvYrepN",
    "aws_user_pools_web_client_id": "24v41e47obsv61t4skvmrh12oi",
    "aws_appsync_graphqlEndpoint": "https://dvjdmdbfvjgcdnkvsg6tted2yq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
